change cpufreq governor to schedutil
tpwrules/nixos-m1 pull request #7
Opened 2022-05-16 22:04 UTC by zzywysm

On arm64 machines, especially those with E and P cores, it's better to go with "schedutil" not "ondemand".  See https://blog.elementary.io/elementary-os-on-pinebook-pro/ for more context.

2022-05-26 03:29 UTC, tpwrules requested changes

2022-05-26 03:29 UTC, tpwrules commented on nix/m1-support/kernel/config
> +CONFIG_HIBERNATION=n
I'm unsure how these changes relate to the governor change. Are sleep and hibernation broken in the current kernel? I'd prefer that they be a separate commit if so.

2022-05-26 03:29 UTC, tpwrules commented on nix/m1-support/kernel/default.nix
> +    powerManagement.cpuFreqGovernor = lib.mkDefault "schedutil";
Please change the comment to indicate why schedutil was chosen over the default ondemand.

Please also remove the `lib.mkDefault`. If it's present, a user who follows the guide to install a new system will get an error that there is a conflicting definition for the option as `nixos-generate-config` puts ondemand by default.

2022-06-21 16:33 UTC, zzywysm commented on nix/m1-support/kernel/default.nix
> +    powerManagement.cpuFreqGovernor = lib.mkDefault "schedutil";
fixed in subsequent commit

2022-06-21 17:40 UTC, zzywysm commented
I have made a mess of things.  I'll resubmit this in a new pull request.

2022-06-21 17:40 UTC, closed without merging